//
// Generated file, do not edit! Created by opp_msgtool 6.0 from QueueHowManyMsg.msg.
//

#ifndef __QUEUEHOWMANYMSG_M_H
#define __QUEUEHOWMANYMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class QueueHowManyMessage;
/**
 * Class generated from <tt>QueueHowManyMsg.msg:16</tt> by opp_msgtool.
 * <pre>
 * message QueueHowManyMessage
 * {
 *     int howMany;
 * }
 * </pre>
 */
class QueueHowManyMessage : public ::omnetpp::cMessage
{
  protected:
    int howMany = 0;

  private:
    void copy(const QueueHowManyMessage& other);

  protected:
    bool operator==(const QueueHowManyMessage&) = delete;

  public:
    QueueHowManyMessage(const char *name=nullptr, short kind=0);
    QueueHowManyMessage(const QueueHowManyMessage& other);
    virtual ~QueueHowManyMessage();
    QueueHowManyMessage& operator=(const QueueHowManyMessage& other);
    virtual QueueHowManyMessage *dup() const override {return new QueueHowManyMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual int getHowMany() const;
    virtual void setHowMany(int howMany);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const QueueHowManyMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, QueueHowManyMessage& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline QueueHowManyMessage *fromAnyPtr(any_ptr ptr) { return check_and_cast<QueueHowManyMessage*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __QUEUEHOWMANYMSG_M_H

