//
// Generated file, do not edit! Created by opp_msgtool 6.0 from QueueQuitMsg.msg.
//

#ifndef __QUEUEQUITMSG_M_H
#define __QUEUEQUITMSG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0600
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class QueueQuitMsg;
// cplusplus {{
#include "Child.h"
// }}

/**
 * Class generated from <tt>QueueQuitMsg.msg:25</tt> by opp_msgtool.
 * <pre>
 * message QueueQuitMsg
 * {
 *     Child child;
 * }
 * </pre>
 */
class QueueQuitMsg : public ::omnetpp::cMessage
{
  protected:
    Child child;

  private:
    void copy(const QueueQuitMsg& other);

  protected:
    bool operator==(const QueueQuitMsg&) = delete;

  public:
    QueueQuitMsg(const char *name=nullptr, short kind=0);
    QueueQuitMsg(const QueueQuitMsg& other);
    virtual ~QueueQuitMsg();
    QueueQuitMsg& operator=(const QueueQuitMsg& other);
    virtual QueueQuitMsg *dup() const override {return new QueueQuitMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const Child& getChild() const;
    virtual Child& getChildForUpdate() { return const_cast<Child&>(const_cast<QueueQuitMsg*>(this)->getChild());}
    virtual void setChild(const Child& child);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const QueueQuitMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, QueueQuitMsg& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

inline any_ptr toAnyPtr(const Child *p) {if (auto obj = as_cObject(p)) return any_ptr(obj); else return any_ptr(p);}
template<> inline Child *fromAnyPtr(any_ptr ptr) { return ptr.get<Child>(); }
template<> inline QueueQuitMsg *fromAnyPtr(any_ptr ptr) { return check_and_cast<QueueQuitMsg*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __QUEUEQUITMSG_M_H

